jonhue/acts_as_favoritor

lib/acts_as_favoritor/favoritable.rb, lib/acts_as_favoritor/favoritor.rb
=> [#15] undefined method `[]' for nil:NilClass when caching enabled

lib/acts_as_favoritor/favoritable.rb, lib/acts_as_favoritor/favoritor.rb
=> [#18] Caching not working correctly

README.md
=> [#10] Update README.md

Gemfile.lock, lib/acts_as_favoritor/version.rb
=> [#27] Release 2.1.0

README.md
=> [#33] Improve README.md

lib/acts_as_favoritor/favoritor.rb, test/acts_as_favoritor_test.rb
=> [#35] Undefined method '+' for :scope:Symbol

Gemfile.lock, lib/acts_as_favoritor/version.rb
=> [#37] 2.1.1

.automerge.yml
=> [#55] Enable auto merge

Gemfile.lock, lib/acts_as_favoritor/version.rb
=> [#57] Release 2.1.2

Gemfile.lock, lib/acts_as_favoritor/version.rb
=> [#64] Release 3.0.0

README.md, lib/acts_as_favoritor/configuration.rb, lib/acts_as_favoritor/favoritable.rb, lib/acts_as_favoritor/favorite_scopes.rb, lib/acts_as_favoritor/favoritor.rb, lib/acts_as_favoritor/favoritor_lib.rb, lib/generators/templates/initializer.rb, lib/generators/templates/migration.rb.erb, lib/generators/templates/model.rb, spec/integration/acts_as_favoritable_spec.rb, spec/integration/acts_as_favoritor_spec.rb, spec/lib/acts_as_favoritor/configuration_spec.rb, spec/lib/acts_as_favoritor/favoritable_spec.rb, spec/lib/acts_as_favoritor/favorite_scopes_spec.rb, spec/lib/acts_as_favoritor/favoritor_lib_spec.rb, spec/lib/acts_as_favoritor/favoritor_spec.rb, spec/support/rails_app/app/models/composer.rb, spec/support/rails_app/app/models/favorite.rb
=> [#63] Write unit tests

Gemfile.lock, lib/acts_as_favoritor/version.rb
=> [#67] Release 4.0.0

README.md
=> [#69] Fix readme

lib/acts_as_favoritor/favoritor.rb
=> [#71] undefined local variable or method `scope` when cache is used

.travis.yml, Gemfile.lock, lib/acts_as_favoritor/version.rb
=> [#73] Release 4.0.1

lib/acts_as_favoritor/favoritor.rb
=> [#77] Undefined local variable or method `favoritable' when using caching

Gemfile.lock, lib/acts_as_favoritor/version.rb
=> [#83] Release 4.0.2

.github/auto-merge.yml, .github/workflows/release.yml, CHANGELOG.md, README.md
=> [#107] Release workflow

README.md, lib/acts_as_favoritor/version.rb
=> [#110] Release 4.0.3

.github/workflows/ci.yml, .rspec, .rubocop.yml, CHANGELOG.md, README.md, lib/acts_as_favoritor/favoritable.rb, lib/acts_as_favoritor/favoritor.rb, lib/acts_as_favoritor/favoritor_lib.rb, spec/integration/acts_as_favoritable_spec.rb, spec/integration/acts_as_favoritor_spec.rb, spec/lib/acts_as_favoritor/favoritable_spec.rb, spec/lib/acts_as_favoritor/favorite_scopes_spec.rb, spec/lib/acts_as_favoritor/favoritor_lib_spec.rb, spec/lib/acts_as_favoritor/favoritor_spec.rb
=> [#136] Allow either a single `scope` or multiple `scopes` to be given

CHANGELOG.md, lib/acts_as_favoritor/version.rb
=> [#138] Release 5.0.0

lib/acts_as_favoritor/version.rb
=> release 6.0.2
